name: roman_converter
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:

dev_dependencies:
  sizzle_lints: ^2.0.2
  test: ^1.25.5
