name: gilded_rose
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  approval_tests: ^0.4.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.5
