name: starter
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  approval_tests: ^0.4.4 

dev_dependencies:
  sizzle_lints: ^2.0.2
  test: ^1.24.0
